/**
 * Local HTTP LLM provider
 * For open-source models running locally
 */

import { LLMProvider } from '../types';

export const localHttpProvider: LLMProvider = {
  id: 'localHttp',
  displayName: 'Local HTTP Server',
  isOnlineService: false,

  async generateSummary(input) {
    // TODO: Implement actual HTTP call to local LLM server
    return {
      shortSummary: 'This is a test summary generated by local LLM.',
      detailedSummarySections: [
        {
          title: 'Key Points',
          bullets: ['Point 1', 'Point 2'],
        },
      ],
      decisions: ['Decision 1'],
      risks: ['Risk 1'],
      followUpQuestions: ['Question 1?'],
    };
  },

  async suggestReply(input) {
    return {
      replyText: 'This is a suggested reply based on the conversation context.',
      rationale: 'Generated using local LLM model.',
    };
  },

  async generateFollowup(input) {
    return {
      questions: [
        'Can you elaborate on that point?',
        'What are the next steps?',
        'How does this align with our goals?',
      ],
    };
  },

  async extractActionItems(input) {
    return {
      actionItems: [
        {
          text: 'Sample action item from conversation',
          owner: null,
          dueDate: null,
          priority: 'medium' as const,
        },
      ],
    };
  },

  async analyzeRisks(input) {
    return {
      risks: [
        {
          description: 'Sample risk identified in conversation',
          severity: 'medium' as const,
        },
      ],
    };
  },

  async transformTone(input) {
    return {
      transformedText: `Transformed version: ${input.originalText}`,
    };
  },
};
